### PR TITLE
Update for PureScript 0.9.x

### PR DESCRIPTION
**Pull request by garyb**
Along with updating the dependencies and some minor code fixes for PS 0.9 I took a few other liberties:
- Updated the build to use a versioned compiler, and `purescript-psa` to turn warnings into errors
- Deleted the `docs` in favour of linking to the library on pursuit
- Added an `MIT` SPDX license to the `bower.json` (a license is required for publishing on pursuit - if you'd rather a different license I can update accordingly)

Thanks!

### CODE REVIEW

**Comment by garyb** [comment]
Ping! (sorry, we depend on this so it would be good to get it up to date rather than depending on a fork)

**Comment by DavidHarrison** [comment]
Thanks for the pull request! Sorry I've been away backpacking, I'll get it merged.

**Comment by garyb** [comment]
Ah nice :smile:

Could you tag a new release too please?

**Comment by DavidHarrison** [comment]
Sorry for the delay, it should be tagged now.

**Pull request merged**
